title: Лекції
description: Колекція текстів лекцій.
baseurl: "/talks" # The subpath of your site, e.g. /blog
url: "https://paulbaumer.github.io" # The base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude: 
  - vendor
  - talk-entity-extractor
  - talk-entity-extractor.skill

# include:
#   - _meta
