title: Лекції
description: Колекція текстів лекцій.
baseurl: "/lectures" # The subpath of your site, e.g. /blog
url: "https://paulbaumer.github.io" # The base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude: 
  - lecture-entity-extractor
  - lecture-entity-extractor.skill
